package_names = [ "Piekarnia Piwo≈Ñski Staffa", "Oskroba Kasprowicza", "Piekarnia Wawerska Conrada", "Piekarnia Wawerska Broniewskiego" ]
telegram = {chat_id=-1001354632445, dev_chat_id=1563082916}
location = {latitude=52.279450, longitude=20.936990, radius=5000}
